package testdata

import (
	"bufio"
	"bytes"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

const (
	dryRun = false

	lineWantRegexpStr    = `.+\.go:[0-9]+: (.+):([0-9]+):[0-9]+: diagnostic "(.+)" does not match pattern .+`
	pkgFactWantRegexpStr = `.+\.go:[0-9]+: (.+):([0-9]+):[0-9]+: fact "{package [^ ]+ \([^)]+\) (.+)}" does not match pattern .+`
	// structure regexp so that it will not match lines matched by pkgFactWantRegexpStr.
	// Should be safe as object facts should not start with '{'.
	objFactWantRegexpStr = `.+\.go:[0-9]+: (.+):([0-9]+):[0-9]+: fact "([^{].+)" does not match pattern .+`
	// matches the object identifier within an objFact expected value in the form of ".<name>:" or "<name>:" where <name> is a valid identifier
	objIdentifierRegexpStr = `\.?([^.]+):`
)

// TestRegenerateTestFiles regenerates the test files to match the output in the file "failure_output.txt". This is
// useful for updating the test files in cases where the output changes, or adding the expected output to test files.
//
// The test file at "safelogging/analyzer_test.go" specifies the packages on which to run. If there are any test
// failures (such as expectations that are not met), they are printed to stdout when run. The full failure output
// (including setup calls and other test runs that are successful) can be copy-pasted into the "failure_output.txt"
// file.
//
// When this test ("TestRegenerateTestFiles") is run, it parses the output of "failure_output.txt" and updates the
// corresponding test file (the path to the proper test file is determined by parsing the output line) with the proper
// output. The "updating" of the test file is performed by finding the comment on the line in question and replacing the
// content, so this logic only works if there is already a comment on the line.
//
// A successful workflow iteration generally looks like the following:
//  1. Write new tests or modify an existing test and put placeholder assertion comments on lines that should be flagged
//  2. Run the tests in "safelogging/analyzer_test.go" -- it should fail and print the reasons for failure
//  3. Copy the test output and paste it into the file at "safelogging/testdata/failure_output.txt" (create if needed)
//  4. Run the "TestRegenerateTestFiles" test
//  5. Run the tests in "safelogging/analyzer_test.go" -- it should succeed
//
// If the test still fails at step (5), it is most likely due to the test file not having a placeholder comment on the
// lines that fail.
//
// Issues flagged on each line should have a trailing placeholder comment such as "// want `zzz`".
// Expected facts for a package should have a placeholder comment on line 1 (the package declaration) of the form
// "// want package:`zzz`".
//
// Ideally, it would be preferable for "safelogging/analyzer_test.go" to simply have a "regenerate" mode where, if
// enabled, it updates the test files -- this would eliminate the need to manually copy-paste test output as is required
// by the current workflow. However, this is difficult to do: the failure output is generated by logic in the
// "golang.org/x/tools/go/analysis/analysistest" package, which uses the "analysistest.Testing.Log" function to log
// output. This output goes to a special test logger that happens to also write its output to stdout, but the manner in
// which this initialization happens makes it difficult to capture this output externally (reading from stdout
// in-process does not work, presumably because the test logger gets a handle to stdout before the test logic can swap
// it out with a pipe to capture output). Although this could be handled by doing something like running the analysis
// test in a separate process and capturing its output, the extra complexity doesn't seem worth it.
func TestRegenerateTestFiles(t *testing.T) {
	testOutput, err := os.ReadFile("failure_output.txt")
	require.NoError(t, err)

	lineWantRegexp := regexp.MustCompile(lineWantRegexpStr)
	pkgFactWantRegexp := regexp.MustCompile(pkgFactWantRegexpStr)
	objFactWantRegexp := regexp.MustCompile(objFactWantRegexpStr)
	objIdentifierRegexp := regexp.MustCompile(objIdentifierRegexpStr)

	updatedLineComments := make(map[string]map[int]string)
	scanner := bufio.NewScanner(bytes.NewBuffer(testOutput))
	for scanner.Scan() {
		line := scanner.Text()

		if lineWantMatches := lineWantRegexp.FindStringSubmatch(line); lineWantMatches != nil {
			filePath := lineWantMatches[1]
			fileMap, ok := updatedLineComments[filePath]
			if !ok {
				fileMap = make(map[int]string)
				updatedLineComments[filePath] = fileMap
			}
			lineNum, err := strconv.Atoi(lineWantMatches[2])
			require.NoError(t, err)
			fileMap[lineNum] = formatWantLine(lineWantMatches[3])
		}

		if pkgFactWantMatch := pkgFactWantRegexp.FindStringSubmatch(line); pkgFactWantMatch != nil {
			filePath := pkgFactWantMatch[1]
			fileMap, ok := updatedLineComments[filePath]
			if !ok {
				fileMap = make(map[int]string)
				updatedLineComments[filePath] = fileMap
			}
			lineNum, err := strconv.Atoi(pkgFactWantMatch[2])
			require.NoError(t, err)
			fileMap[lineNum] = formatPkgFactLine(pkgFactWantMatch[3])
		}

		if objFactWantMatch := objFactWantRegexp.FindStringSubmatch(line); objFactWantMatch != nil {
			filePath := objFactWantMatch[1]
			fileMap, ok := updatedLineComments[filePath]
			if !ok {
				fileMap = make(map[int]string)
				updatedLineComments[filePath] = fileMap
			}

			lineNum, err := strconv.Atoi(objFactWantMatch[2])
			require.NoError(t, err)

			objName := "[No object name found]"
			objFactValueAfterFact := objFactWantMatch[3]
			if objNameMatches := objIdentifierRegexp.FindStringSubmatch(objFactValueAfterFact); len(objNameMatches) >= 2 {
				objName = objNameMatches[1]
			}
			fileMap[lineNum] = formatObjFactLine(objName, objFactValueAfterFact)
		}
	}

	testFiles := slices.Collect(maps.Keys(updatedLineComments))
	sort.Strings(testFiles)
	for _, currTestFile := range testFiles {
		currLineNum := 0
		outputBytesBuf := &bytes.Buffer{}
		inputBytes, err := os.ReadFile(currTestFile)
		require.NoError(t, err)

		for {
			currLineNum++
			newlineIdx := bytes.IndexByte(inputBytes, '\n')
			if newlineIdx == -1 {
				break
			}
			currLine := append([]byte{}, inputBytes[:newlineIdx]...)
			inputBytes = inputBytes[newlineIdx+1:]
			if updatedComment, ok := updatedLineComments[currTestFile][currLineNum]; ok {
				if idx := bytes.Index(currLine, []byte("// want ")); idx != -1 {
					currLine = append(currLine[:idx], []byte(updatedComment)...)
					currLine = append(currLine)
				}
			}
			_, _ = outputBytesBuf.Write(currLine)
			_ = outputBytesBuf.WriteByte(byte('\n'))
		}
		outputBytesBuf.Write(inputBytes)

		if !dryRun {
			err = os.WriteFile(currTestFile, outputBytesBuf.Bytes(), 0644)
			require.NoError(t, err)
		}
		fmt.Printf("%s:\n", currTestFile)
		fmt.Println(outputBytesBuf.String())
	}
}

var atFilePathRegexp = regexp.MustCompile(`at (.+` + regexp.QuoteMeta(string(filepath.Separator)) + `)?(.+\.go):[0-9]+:[0-9]+`)

func substituteRegexpForGopath(in string) string {
	matches := atFilePathRegexp.FindStringSubmatchIndex(in)
	if len(matches) == 0 {
		return in
	}
	return in[:matches[2]] + `.+` + in[matches[3]:]
}

func formatWantLine(content string) string {
	return "// want `^" + substituteRegexpForGopath(translateToInsertableString(content)) + "$`"
}

func formatPkgFactLine(content string) string {
	return "// want package:`" + translateToInsertableString(content) + "`"
}

func formatObjFactLine(objName, content string) string {
	return "// want " + objName + ":`" + translateToInsertableString(content) + "`"
}

func translateToInsertableString(in string) string {
	in = strings.Replace(in, `\"`, `"`, -1)
	in = strings.Replace(in, `\\`, `\`, -1)
	return regexp.QuoteMeta(in)
}
